on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - name: 'testing actions'
        run: pwd

      - name: 'testing printing'
        run: echo khaled
 